// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3luG6GyiDKqegshZDldQKtoecyR5Og7g',
    appId: '1:770909967004:web:691edfd24632cd8ad69359',
    messagingSenderId: '770909967004',
    projectId: 'sentilytics-app',
    authDomain: 'sentilytics-app.firebaseapp.com',
    storageBucket: 'sentilytics-app.firebasestorage.app',
    measurementId: 'G-9E42PP8ZEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLCuS3wR8Hle5Z1c9bhpiWbZnOJVqYNUg',
    appId: '1:770909967004:android:4d0d9e6a51bd5254d69359',
    messagingSenderId: '770909967004',
    projectId: 'sentilytics-app',
    storageBucket: 'sentilytics-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9t0yD6EI4CbxyoQJ5WDFU5B9UaGTDmoU',
    appId: '1:770909967004:ios:09aae182f4a7a160d69359',
    messagingSenderId: '770909967004',
    projectId: 'sentilytics-app',
    storageBucket: 'sentilytics-app.firebasestorage.app',
    iosClientId: '770909967004-intpltdn9cqdktqcbdr58af3jg6mo5rj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sentilytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9t0yD6EI4CbxyoQJ5WDFU5B9UaGTDmoU',
    appId: '1:770909967004:ios:09aae182f4a7a160d69359',
    messagingSenderId: '770909967004',
    projectId: 'sentilytics-app',
    storageBucket: 'sentilytics-app.firebasestorage.app',
    iosClientId: '770909967004-intpltdn9cqdktqcbdr58af3jg6mo5rj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sentilytics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3luG6GyiDKqegshZDldQKtoecyR5Og7g',
    appId: '1:770909967004:web:ff94931eb5063920d69359',
    messagingSenderId: '770909967004',
    projectId: 'sentilytics-app',
    authDomain: 'sentilytics-app.firebaseapp.com',
    storageBucket: 'sentilytics-app.firebasestorage.app',
    measurementId: 'G-D5CSR13QXR',
  );
}
